config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'tags/:name' => 'tags#show', as: 'tag_show'
  devise_for :users
  root to: 'companies#index'
  resources :users, except: [:show]
  resources :companies do
    resources :stories do
      # collection do
      # get 'tags/:name' => 'tags#show', as: 'tag_show'
      # end
      # collection do
      #   get 'search'
      # end
      resources :messages, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :story, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like

  def create
    @like = current_user.likes.new(story_id: params[:story_id])
    @like.save
  end

  def destroy
    like = current_user.likes.find_by(story_id: params[:story_id])
    like.destroy
  end

  private

  def set_like
    @story = Story.find(params[:story_id])
    @company = Company.find(params[:company_id])
    @likes = Like.where(story_id: params[:story_id])
    @id_like = "#like-link-#{@story.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likeLinks.haml
.likeLink{id: "like-link-#{story.id}"}
  - if user_signed_in?
    - if current_user.likes.find_by(story_id: story.id)
      = button_to company_story_like_path(@company.id, story.id, likes), method: :delete, id: "like-button", remote: true do
        %a
          %i.fa.fa-heart
          %span.likesCount
            = story.likes.count
    - else
      = button_to company_story_likes_path(company.id, story.id), id: "like-button", remote: true do
        %a
          %i.fa.fa-heart-o
          %span.likesCount
            = story.likes.count
  - else
    %a.notSignIn
      %i.fa.fa-heart-o
      %span
        = story.likes.count

app/views/likes/create.js.erb
$("<%= @id_like %>").html('<%= j(render(partial: "likes/likeLinks", locals: { company: @company, story: @story, likes: @likes, like: @like })) %>');

app/views/likes/destroy.js.erb
$("<%= @id_like %>").html('<%= j(render(partial: "likes/likeLinks", locals: { company: @company, story: @story})) %>');