config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'tags/:name' => 'tags#show', as: 'tag_show'
  devise_for :users
  root to: 'companies#index'
  resources :users, except: [:show]
  resources :companies do
    resources :stories do
      # collection do
      # get 'tags/:name' => 'tags#show', as: 'tag_show'
      # end
      # collection do
      #   get 'search'
      # end
      resources :messages, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_flash.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_header.haml
%header#header
  #global-header
    #logo
      %a{href: "/"}
        = image_tag "https://www.pr-table.com/assets/logo.svg", alt: "PR Table"
    %nav#g-nav
      %ul
        %li
          %a{:href => ""} ストーリー
        %li
          %a{:href => ""} 企業
        %li
          %a#topic-trigger{:href => ""} トピック
        %li
          %a{:href => "", :target => "_blank"} PR Tableとは？
    .buttons
      #create
        - unless user_signed_in?
          = link_to ""
        - else
          - if current_user.company_id == nil
            = link_to "会社を登録", new_company_path, class: 'btn'
          - else
            = link_to "ストーリー作成", new_company_story_path(current_user.company_id), class: 'btn'
      #login
        - unless user_signed_in?
          = link_to "ログイン / 新規登録", new_user_session_path, class: 'btn'
        - else
          = link_to "アカウント編集/ログアウト", edit_user_registration_url(current_user), class: 'btn'
      #search
        = render 'layouts/searchForm'
.top__header-tags
  %ul
    %li
      %a{:href => ""}
    /
      <li><a href="/tag/research-development">#研究開発</a></li>
      <li><a href="/tag/member">#社員・職員</a></li>
      <li><a href="/tag/ipo">#IPO</a></li>
      <li><a href="/tag/csr">#CSR・社会貢献活動</a></li>
      <li><a href="/tag/internet-of-things">#IoT</a></li>
      <li><a href="/tag/kumamoto">#熊本</a></li>
      <li><a href="/tag/brother">#兄弟</a></li>
      <li><a href="/tag/tokyo-olympic">#東京五輪2020</a></li>

app/views/layouts/_signUpPage.haml
.signUp
  .signUp__wrap
    %section.signUp__wrap__brand
      .signUp__wrap__brand--inner
        .signUp__wrap__brand--inner-img
          = image_tag "https://product.pr-table.com/upimgs/lp_images/pcsp.png", class: "signUp-topImg"
        .signUp__wrap__brand--inner-copy
          %h1 ストーリーで共感を生む
          %p 新しいPRのソリューション
          .signUp__wrap__brand--inner-copy-btn
            %a.signUpTopBtn{:href => "#form"} 資料請求
    %section.signUp__wrap__firstContents
      .signUp__wrap__firstContents--inner.signUp-innerDes
        .signUp__wrap__firstContents--inner-title
          %h2.middleHeadline 多くの地方・中小企業から上場企業に選ばれています
          %p.smallHeadline ブランドを社内外に発信するためにPR Tableが活用されています
        .signUp__wrap__firstContents--inner-companyList
          %figure
            %img
              = image_tag "https://product.pr-table.com/upimgs/lp_images/logos.png?eeerere"
    %section.signUp__wrap__secondContents
      .signUp__wrap__secondContents--inner.signUp-innerDes
        .signUp__wrap__secondContents--inner-title
          %h2.middleHeadline ストーリーテリングの時代
          %p.smallHeadline 生活者は、企業自らが語るストーリーを求めています
        .signUp__wrap__secondContents--inner-content
          .signUp__wrap__secondContents--inner-content-img
            %img
              = image_tag "https://product.pr-table.com/upimgs/lp_images/graph.png"
          .signUp__wrap__secondContents--inner-content-des
            %figure
              %p.signUp-p 「企業のウェブサイトに訪れた際に、詳しくサイトを見てみたいと思わせる要素」という質問に対して、最も多く回答されたのは「開発秘話・背景などストーリー性があるコンテンツが掲載されている」です（※）。これにより、企業自らが会社・製品のストーリーを語る必要が迫られているといえます。
              %p.signUp-p{:style => "margin-top: 2em;"} ※ 企業広報戦略&落語研究会（電通PR内）「第1回企業やら魅力度調査」による（対象：生活者10,000人／2016年）
    %section.signUp__wrap__thirdContents
      .signUp__wrap__thirdContents--inner.signUp-innerDes
        .signUp__wrap__thirdContents--inner-pointWrap
          .signUp__wrap__thirdContents--inner-pointWrap-left
            .signUp__wrap__thirdContents--inner-pointWrap-left-img
              %img
                = image_tag "https://product.pr-table.com/upimgs/lp_images/demo01.png"
            .signUp__wrap__thirdContents--inner-pointWrap-left-des
              %h3.middleHeadline PRのプロが行き着いたサービス
              %p.signUp-p プレスリリースやメディアリレーションズだけがPR・広報の手法ではありません。事業会社やPR会社でPR・広報を経験したメンバーが運営する「PR Table」は、ストーリーを発信することで、ステークホルダー（※）と良好な関係を構築するためのサービスです。
              %p.signUp-p ※ 顧客・ユーザー、株主・投資家、学生やキャリア転職をしたい求職者、社員・従業員など
          .signUp__wrap__thirdContents--inner-pointWrap-right
            .signUp__wrap__thirdContents--inner-pointWrap-right-wrap
              .signUp__wrap__thirdContents--inner-pointWrap-right-wrap-img
                %img
                  = image_tag "https://product.pr-table.com/upimgs/lp_images/demo02.png"
              .signUp__wrap__thirdContents--inner-pointWrap-right-wrap-des
                %h3.middleHeadline 1ページで魅せる会社のカルチャー・文化
                %p.signUp-p 「PR Table」ではストーリーだけではなく、会社の想い出がつまったアルバムや、ブランドの歴史をヒストリー形式で効果的に伝えることができる機能を用意しています。また、「どう伝えたらいいか？」にお困りの際はPRコンサルタントがサポートいたします。
          .signUp__wrap__thirdContents--inner-pointWrap-left
            .signUp__wrap__thirdContents--inner-pointWrap-left-img
              %img
                = image_tag "https://product.pr-table.com/upimgs/lp_images/demo03.png"
            .signUp__wrap__thirdContents--inner-pointWrap-left-des
              %h3.middleHeadline 共感によるマッチングが生まれる場所
              %p.signUp-p 企業ページやストーリーには「採用エントリー」「事業紹介」「取材依頼」を促進するボタンを設置できます。ストーリーを通じて会社のブランドを伝えることで、深い理解や共感を得ることができ、お互いミスマッチのない関係を構築するきっかけとなります。
    %section.signUp__wrap__fourthContents
      .signUp__wrap__fourthContents--inner.signUp-innerDes
        .signUp__wrap__fourthContents--inner-title
          %h2.middleHeadline PR Tableの主な機能・サービス
          %p.smallHeadline 継続的にストーリーテリングを行うための仕組みを開発しています
        .signUp__wrap__fourthContents--inner-function
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-compose
            %p ストーリー作成
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.fa.fa-bar-chart{"aria-hidden" => "true"}
            %p アナリティクス
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-calendar
            %p 沿革作成
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-images
            %p アルバム管理
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-iphone
            %p スマホ対応
        .signUp__wrap__fourthContents--inner-function
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-person-add
            %p チーム運用
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-document
            %p
              プレスリリース
              %br/
              メディア掲載管理
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
            %p
              電話・チャット
              %br/
              メールサポート
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-person-stalker
            %p PRコンサルティング
          .signUp__wrap__fourthContents--inner-function-list
            .signUp__wrap__fourthContents--inner-function-list-icon
              %i.ion-plus
            %p 新機能を順次追加
          %link{href: "http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css", rel: "stylesheet"}
    %section.signUp__wrap__fifthContents
      .signUp__wrap__fifthContents--inner.signUp-innerDes
        .signUp__wrap__fifthContents--inner-title
          %h2.middleHeadline サクセスストーリー
          %p.signUp-p 採用広報、インターナルコミュニケーションで効果が出ています
        .signUp__wrap__fifthContents--inner-success
          - 1.upto(3) do |i|
            .signUp__wrap__fifthContents--inner-success-list
              .signUp__wrap__fifthContents--inner-success-list-topBlock
                .signUp__wrap__fifthContents--inner-success-list-topBlock-img{:style => "background-image:url(https://t.pimg.jp/021/543/870/1/21543870.jpg);"}
                .signUp__wrap__fifthContents--inner-success-list-topBlock-info
                  %strong ギークス株式会社
                  %p 経営企画室 広報　松井瑞恵 様
              .signUp__wrap__fifthContents--inner-success-list-des 経営陣の想いや社員それぞれが主役となり活躍していることをストーリーとして言語化したことで、社員の共感を生むことができ、自然とSNSや社外へ向けたシェア・伝播を自然に行うことが定着してきました。
              .signUp__wrap__fifthContents--inner-success-list-more
                %a.signUpMiddleBtn{:href => ""} ストーリーをみる
    %section#form.signUp__wrap__sixthContents
      .signUp__wrap__sixthContents--inner.signUp-innerDes
        .signUp__wrap__sixthContents--inner-content
          %h2.middleHeadline ストーリーテリングをはじめてみませんか？
          %p.smallHeadline 月額4万円から導入できるリーズナブルなプランをご用意しています
          .signUp__wrap__sixthContents--inner-content-form
            .signUp__wrap__sixthContents--inner-content-form-run
              = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
                = devise_error_messages!
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "会社名"
                /     %span 必須
                /   .signUpFieldInput
                /     = f.text_field :name, class: 'signUpFieldInput-inner'
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "部署・役職"
                /     %span.span2 不要
                /   .signUpFieldInput
                /     .signUpFieldInput-inner.inner2
                .signUpField
                  .signUpFieldLabel
                    = f.label :name, "お名前"
                    %span 必須
                  .signUpFieldInput
                    = f.text_field :name, class: 'signUpFieldInput-inner'
                    / %input{"data-formrun-class-if-error" => "has-danger", "data-formrun-required" => "", :name => "お名前", :type => "text"}/
                    / .signUp__wrap__sixthContents--error{"data-formrun-show-if-error" => "お名前"} お名前を入力してください
                .signUpField
                  .signUpFieldLabel
                    = f.label :email, "メールアドレス"
                    %span 必須
                  .signUpFieldInput
                    = f.email_field :email, autofocus: true, class: 'signUpFieldInput-inner'
                .signUpField
                  .signUpFieldLabel
                    = f.label :password, "パスワード"
                    %span 必須
                  .signUpFieldInput
                    = f.password_field :password, autocomplete: "off", class: 'signUpFieldInput-inner'
                .signUpField
                  .signUpFieldLabel
                    = f.label :password_confirmation, "パスワード(再確認)"
                    %span 必須
                  .signUpFieldInput
                    = f.password_field :password_confirmation, autocomplete: "off", class: 'signUpFieldInput-inner'
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "電話番号"
                /     %span.span2 不要
                /   .signUpFieldInput
                /     .signUpFieldInput-inner.inner2
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "会社URL"
                /   .signUpFieldInput.inner2
                /     = f.text_field :name, class: 'signUpFieldInput-inner'
                /     / %input{:name => "会社URL", :type => "text"}/
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "お問い合わせ内容"
                /     %span.span2 不要
                /   .signUpFieldWrap
                /     .signUpFieldCheckboxes
                /       .signUpFieldCheckbox
                /         / %input#inqtype{"data-formrun-required" => "", :name => "お問い合わせ内容[]", :type => "checkbox", :value => "サービス詳細"}/
                /         = f.label :name, "サービス詳細", class: "checkboxInner"
                /       .signUpFieldCheckbox
                /         / %input#inqtype{"data-formrun-required" => "", :name => "お問い合わせ内容[]", :type => "checkbox", :value => "導入事例"}/
                /         = f.label :name, "導入事例", class: "checkboxInner"
                /       .signUpFieldCheckbox.mt
                /         / %input#inqtype{"data-formrun-required" => "", :name => "お問い合わせ内容[]", :type => "checkbox", :value => "サービス利用料"}/
                /         = f.label :name, "サービス利用料", class: "checkboxInner"
                /       .signUpFieldCheckbox.mt
                /         / %input#inqtype{"data-formrun-required" => "", :name => "お問い合わせ内容[]", :type => "checkbox", :value => "その他"}/
                /         = f.label :name, "その他", class: "checkboxInner"
                /     / .signUp__wrap__sixthContents--wrap-form-error{"data-formrun-show-if-error" => "お問い合わせ内容[]"} お問い合わせ内容を選択してください
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "課題"
                /     %span 必須
                /   .signUpFieldInput
                /     %select{"data-formrun-class-if-error" => "has-danger", "data-formrun-required" => "", :name => "課題"}
                /       %option{value: ""} 選択してください
                /       %option{value: "企業広報"} 企業広報
                /       %option{value: "採用広報"} 採用広報
                /       %option{value: "社内コミュニケーション"} 社内コミュニケーション
                /       %option{value: "投資家向け広報"} 投資家向け広報
                /       %option{value: "CSR"} CSR
                /     / #signUpError{"data-formrun-show-if-error" => "課題"} 課題を選択してください
                / .signUpField
                /   .signUpFieldLabel
                /     = f.label :name, "備考"
                /   .signUpFieldInput
                /     %textarea{:name => "備考"}
                = f.submit "送信", class: "signUpBottomBtn"

app/views/layouts/_storyContent.haml
.breadcrumbsWrap
  %section.breadcrumbsWrap--index
    %a{:href => "/"} HOME
    %a{:href => ""}
      = @story.company.name
    %span
      = @story.title
.container
  %main.container--storyCt{:role => "main"}
    %article.container--storyCt__content
      .container--storyCt__content-author
        %a{:href => ""}
          %figure
            .storyCtTopImg
              / = image_tag "https://www.pr-table.com/upimgs/profile_images/926/medium/b42d77d7c6f5f189a70dce0e7156a31004a4c0e6.png?1501749720", class: 'storyCtTopImgLogo'
              /{"data-original" => "/upimgs/profile_images/926/medium/b42d77d7c6f5f189a70dce0e7156a31004a4c0e6.png?1501749720"}/
            %figcaption
              = @story.company.name
      %h1
        = @story.title
      .container--storyCt__content-socials
        %ul
          %li
            %a.ctFacebook.storyCtIconBox
              / {:href => "http://www.facebook.com/share.php?u=https://www.pr-table.com/raksul/stories/685"}
              %i.fa.fa-facebook
          %li
            %a.ctEight.storyCtIconBox
              / {:href => "https://8card.net/posts/links/new?application_id=60920482208541&url=https://www.pr-table.com/raksul/stories/685"}
              %img{:alt => "eight", :height => "13", :src => "https://materials.8card.net/web/top/images/v8/step8.svg", :width => "19"}/
          %li
            %a.ctTwitter.storyCtIconBox
              / {:href => "http://twitter.com/share?url=https://www.pr-table.com/raksul/stories/685&via=PR_Table&text=働きやすさは「精神的なサポート」に宿る。子育て社員と振り返る、ラクスルの仕組み", :target => "_blank"}
              %i.fa.fa-twitter
          %li
            %a.ctHatena.storyCtIconBox
              / {:href => "http://b.hatena.ne.jp/entry/https://www.pr-table.com/raksul/stories/685"}
              %img{:height => "13", :src => "https://lh3.googleusercontent.com/8A_I8WUzV6NcLv8JP5cJDLL-1EeYwIPeR80ewaiTySdFYiCR3y5CdAkckJBGSR51FYI=w300", :width => "15"}/
          %li
            %a.ctPocket.storyCtIconBox
              / {:href => "http://getpocket.com/edit?url=https://www.pr-table.com/raksul/stories/685&title=働きやすさは「精神的なサポート」に宿る。子育て社員と振り返る、ラクスルの仕組み"}
              %img{:height => "13", :src => "http://your-knowhow.com/mercari/images/sns.area/pocket.mb.png", :width => "15"}/
      %section.container--storyCt__content-topics
        %h2
        %figure
          %p
            = @story.user.name
          .storyCt-img
            = image_tag @story.image
          .storyCt-body
            %p
              = raw @story.body
          #likeLinksForm
            = render partial: 'likes/likeLinks', locals: { company: @company ,story: @story, likes: @likes }
      %section.container--storyCt__content-footer
        .container--storyCt__content-footer-socials
          %ul
            %li
              %a.ftFacebook
                / {:href => "http://www.facebook.com/share.php?u=https://www.pr-table.com/raksul/stories/685"}
                %i.fa.fa-facebook
            %li
              %a.ftEight
                / {:href => "https://8card.net/posts/links/new?application_id=60920482208541&url=https://www.pr-table.com/raksul/stories/685"}
                %img
                  / {:alt => "eight", :height => "13", :src => "/assets/eight.png", :width => "19"}/
            %li
              %a.ftTwitter
                / {:href => "http://twitter.com/share?url=https://www.pr-table.com/raksul/stories/685&via=PR_Table&text=働きやすさは「精神的なサポート」に宿る。子育て社員と振り返る、ラクスルの仕組み", :target => "_blank"}
                %i.fa.fa-twitter
            %li
              %a.ftHatena
                / {:href => "http://b.hatena.ne.jp/entry/https://www.pr-table.com/raksul/stories/685"}
                %img{:height => "13", :src => "", :width => "15"}/
            %li
              %a.ftPocket
                /{:href => "http://getpocket.com/edit?url=https://www.pr-table.com/raksul/stories/685&title=働きやすさは「精神的なサポート」に宿る。子育て社員と振り返る、ラクスルの仕組み"}
                %img
                  / {:height => "13", :src => "/assets/pocket.png", :width => "15"}/
        .container--storyCt__content-footer-infoWrapper
          .ftInfo
            .ftTags
              - tags.each do |tag|
                = link_to "#{tag.name}", tag_show_path(name: tag.name)
            %date
              = @story.created_at.strftime('%Y-%m-%d %H:%M')
        #messageLinksForm
          .ms
            = render partial: 'messages/messageLinks', locals: { company: @company ,story: @story, messages: @messages }
        .container--storyCt__content-footer-profile
          .container--storyCt__content-footer-profile-info
            / {"data-original" => "/upimgs/cover_images/136/large/fe4376c000d3b845906fd4208a3457cbf22954db.jpg?1465265988"}
            .container--storyCt__content-footer-profile-info-background
            .container--storyCt__content-footer-profile-info-companyWrapper
              .companyHead
                .companyLogo
                  %figure
                    .logoImg
                      %a
                        /{:href => "/raksul"}
                        %img
                          / {:src => "/upimgs/profile_images/926/medium/b42d77d7c6f5f189a70dce0e7156a31004a4c0e6.png?1501749720"}/
                    %figcaption.companyName
                      %a
                        / {:href => "/raksul"} ラクスル株式会社
                .companyLink
                  %a
                    / {:href => "/raksul"}
                    %i.fa.fa-chevron-right
                      / {"aria-hidden" => "true"}>
                    / この会社について
              .storyCtBtns
                %ul
                  %li
                    %a.entry
                      / {:href => "https://recruit.raksul.com/guideline/", :onclick => "ga('send', 'event', '働く', 'クリック', 'ラクスル株式会社');", :target => "_blank"}
                      働きたい
                      %i.fa.fa-building-o
                        / {"aria-hidden" => "true"}
                  %li
                    %a.service
                      / {:href => "https://corp.raksul.com/", :onclick => "ga('send', 'event', '事業', 'クリック', 'ラクスル株式会社');", :target => "_blank"}
                      事業を知る
                      %i.fa.fa-line-chart
                        / {"aria-hidden" => "true"}
                  %li
                    %a#inquiry.coverage
                      / {:href => "/reply/685", :onclick => "ga('send', 'event', 'メッセージ', 'クリック', 'ラクスル株式会社');"}
                      取材したい
                      %i.fa.fa-pencil
                        / {"aria-hidden" => "true"}
          .container--storyCt__content-footer-profile-otherStory
            %article
              %a
                / {:href => "/raksul/stories/639"}
                .hoverground
                .storyCtFtImg
                  / {"data-original" => "/upimgs/story_images/3360/large/b6ba3b4837b68b72cce88455b9864372198429ff.jpg?1498105868"}
                / %strong 新卒2年目社員と考えた、急成長のドライバーである「ラクスルらしさ」の正体
                / %p ラクスル株式会社
      / %section.container--storyCt__content-relativeStory
      /   %h3 関連ストーリー
      /   .relativeWrapper
      /     %article
      /       %a
      /         / {:href => "/OpenNetworkLab/stories/607"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/3217/large/961cf9da19b3e2371b666dfe666133f5c45fdfa9.jpg?1496390792"}
      /         %strong シリコンバレーやアジアからの参加からも！ Onlabは世界の起業家とともに未来を創る
      /         %p Open Network Lab
      /     %article
      /       %a
      /         / {:href => "/mobilefactory/stories/519"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/2698/large/b9f48814f10ee66b7cfa8eaecc451fbc30102287.jpg?1490056806"}
      /         %strong 入社1年目でベストクリエイター賞を獲得ーー新卒デザイナー、その活躍の舞台裏
      /         %p 株式会社モバイルファクトリー
      /     %article
      /       %a
      /         / {:href => "/netjinzaibank/stories/92"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/415/large/25688094d35d68617d9e019c13d439d7160f369d.JPG?1452753593"}
      /         %strong NEC、そしてGREE−−本気で世界一を目指していたエンジニアは、なぜ 「NET jinzai bank」 を選んだのか？
      /         %p NET jinzai bank
      /     %article
      /       %a
      /         / {:href => "/sho-pat/stories/644"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/3382/large/f562b6c155a0936e86b34b6ae0daa27b2a8823c3.jpg?1498196692"}
      /         %strong 国際的な視野で描く、知的財産権の未来――弁理士・東谷幸浩の知性とサービス精神
      /         %p 正林国際特許商標事務所
      /     %article
      /       %a
      /         / {:href => "/neo-career/stories/29"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/116/large/c34585f405d9ee359848faf0382a11252416fc2f.jpg?1444706395"}
      /         %strong 子どもたちがオフィスでビジネス体験！？ 社員家族向けイベント「NeoFes」とは？
      /         %p 株式会社ネオキャリア
      /     %article
      /       %a
      /         / {:href => "/wondershake/stories/202"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/939/large/37bd7e04ada4c00d2bf27ff330f577653f7bd951.jpg?1466074001"}
      /         %strong “どん底”から這い上がり、世界に再度挑戦していく――Wondershakeの過去、現在、そして未来
      /         %p 株式会社Wondershake
      /     %article
      /       %a
      /         / {:href => "/miraishokudo/stories/145"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/635/large/9545d6813e7f2d2ca7a9984a5e762c20a4ce4674.jpg?1459752612"}
      /         %strong “善い悪い“の概念を超えて…未来食堂が手がける新サービス「サロン18禁」のカラクリ
      /         %p 未来食堂
      /     %article
      /       %a
      /         / {:href => "/Netprotections/stories/217"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/1038/large/37c7fbaebb319e8608031e628842e6feb42d892a.jpg?1466763421"}
      /         %strong 学生の口コミで広がり人気を得た、サマーインターンシップに込められた想いとは？
      /         %p 株式会社ネットプロテクションズ
      / %section.container--storyCt__content-footer-relativeStory
      /   %h3 注目ストーリー
      /   .relative-wrapper
      /     %article
      /       %a
      /         / {:href => "/raksul/stories/685"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/3597/large/96fc2cb6b57616642135d2eefcb2d2db6019261b.jpg?1501121062"}
      /         %strong 働きやすさは「精神的なサポート」に宿る。子育て社員と振り返る、ラクスルの仕組み
      /         %p ラクスル株式会社
      /     %article
      /       %a
      /         / {:href => "/sakura-ad/stories/672"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/3536/large/cf2b584b07a866b0c6fd39cda965fd55eba5f916.jpg?1500543562"}
      /         %strong 新たな人材・スキルは不要！ IoT事業の可能性を拓く「sakura.io」
      /         %p さくらインターネット株式会社
      /     %article
      /       %a
      /         / {:href => "/OpenNetworkLab/stories/376"}
      /         .hoverground
      /         .storyCtFtImg
      /           / {"data-original" => "/upimgs/story_images/1890/large/d527383b6e118ca7a377701e9312f6dd297e8210.jpg?1479378451"}
      /         %strong 日本の起業家が世界へ羽ばたく支援をーーOpen Network Lab創設者の想い
      /         %p Open Network Lab
      /     %article
      /       %a
      /         / {:href => "/recruitcareer/stories/173"}
      /         .hoverground
      /         .storyCtFtImg
      /         / {"data-original" => "/upimgs/story_images/839/large/6103506186baab360db3fc736c6a0c487cec5174.jpeg?1464009344"}
      /         %strong 「人生は、波瀾万丈なくらいがおもしろい」ーー35年間リクルートと共に歩んだ男の軌跡
      /         %p 株式会社リクルートキャリア